#!/bin/bash
# format [deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>
port=$2
origin=$4
name=$6
username=$8
keyfile=${10}

HTTPServerDirectory='~/HttpServer'
DNSServerDirectory='/home/zhoufan1/rollCDN/DNSServer/'
cdHTTPFolder='cd ~/HttpServer/;'
cdDNSFolder='cd /home/zhoufan1/rollCDN/DNSServer/;'
runDNSServer='./dnsserver -p '$port
runDNSServer+=' -n '$name
runHTTPServer='./httpserver -p '$port
runHTTPServer+=' -o '$origin
catHTTPServer='cat HTTPLOGFILE'
catDNSServer='cat DNSLOGFILE'
DNSLOGDIRECTORY='/home/zhoufan1/rollCDN/DNSServer/DNSLOGFILE'

echo $DNSLOGDIRECTORY
ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu $cdDNSFolder$runDNSServer$' >DNSLOGFILE 2>&1 &'
ssh -i $keyfile $username@cs5700cdnproject.ccs.neu.edu $cdDNSFolder$catDNSServer > ./dnslog
    
ec2host=("ec2-52-0-73-113.compute-1.amazonaws.com" "ec2-52-16-219-28.eu-west-1.compute.amazonaws.com" "ec2-52-11-8-29.us-west-2.compute.amazonaws.com" "ec2-52-8-12-101.us-west-1.compute.amazonaws.com" "ec2-52-28-48-84.eu-central-1.compute.amazonaws.com" "ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com" "ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com" "ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com" "ec2-54-94-214-108.sa-east-1.compute.amazonaws.com")

for hostname in "${ec2host[@]}"
do
	ssh -i $keyfile $username@$hostname $cdHTTPFolder$runHTTPServer$' >HTTPLOGFILE 2>&1 &'
	ssh -i $keyfile $username@$hostname 'chmod 777 '$HTTPServerDirectory
	ssh -i $keyfile $username@$hostname $cdHTTPFolder$catHTTPServer > ./httplog
done
